--- # Webserver
- hosts: server2
  user: test
  sudo: yes
  gather_facts: yes
  tasks:
    - name: Download index.html
      get_url:  url=http://rediff.com/index.html dest=/home/test
    - name: copy index.html
      copy: src=index.html dest=/var/www/html/index.html
    - name: start httpd service
      service: name=httpd state=started
